-- 1. Profiles Table (extends default Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  xp integer default 0,
  level integer default 1,
  streak integer default 0,
  last_login timestamp with time zone,
  badges text[] default '{}'::text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Journal Entries Table
create table public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text,
  content text,
  mood text,
  date date default CURRENT_DATE,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.journal_entries enable row level security;

-- 4. Create Policies (Users can only see/edit their own data)
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can view own journal" on public.journal_entries
  for select using (auth.uid() = user_id);

create policy "Users can insert own journal" on public.journal_entries
  for insert with check (auth.uid() = user_id);

create policy "Users can update own journal" on public.journal_entries
  for update using (auth.uid() = user_id);

create policy "Users can delete own journal" on public.journal_entries
  for delete using (auth.uid() = user_id);

-- 5. Trigger to automatically create a profile after Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
